### ISSUE TITLE
Approach

### ISSUE THREAD

**Issue by ektrah** [core-wg/draft-dns-over-coap#18]
The draft currently seems to implement the following general approach:

1. A CoAP client sends a CoAP request to a DoC proxy
2. The DoC proxy translates the CoAP request to a DNS request and sends that to a DNS server
3. The DNS server returns a DNS response
4. The DoC proxy translates the DNS response to a CoAP response and returns that to the CoAP client

This approach is... suboptimal..., since it uses CoAP on the wrong level IMO: "DNS over CoAP" is presented more or less as a new protocol that happens to reuse many parts of CoAP but comes with a lot of additional, overly-specific requirements. The draft goes into a lot of details of protocol machinery (e.g., CoAP message types, options and features to be used). IMO, the result is unnecessarily rigid (with regards future developments, such as new block options) and annoying to implement (since implementers have to take care that the generic CoAP implementation they're using is issuing requests exactly as specified).

I would like to propose a different approach that would alleviate a lot of these problems, simply by moving the solution up the stack  a bit:

1. A client requests certain DNS information from a server that offers a RESTful DNS API over CoAP
2. The server returns the requested DNS information to the client

This way, all the draft needs to do is to specify a REST API for DNS information, layered on top of CoAP.

How the API is implemented, is an *implementation detail:* An API implementation is free to retrieve the information from a DNS server using DNS, from a local database using SQL, from a DNS resolver on the same machine using some inter-process call, etc. Most likely, an implementation would have a local DNS cache that would be used to answer the API calls directly (if the requested DNS records in the cache are fresh) or that would be updated in one of the above, implementation-specific ways before being used to answer the API calls. Answering a single API call might require several updates to the cache; a single cache update might update several DNS records in the cache at once. 

How the API is used, is a *deployment detail:* Message fragmentation, reliable transmission, choice of security protocol, etc. are all concerns of the of the lower layers. Whether the API is instantiated on a server that is reachable over DTLS or OSCORE, whether the client interacts with the API using confirmable or non-confirmable CoAP requests, whether large messages are transported using CoAP block-wise transfers or CoAP over WebSockets, etc., are out of scope of the API specification.

**Comment by miri64** [comment]
Sorry for the late reply.

We discussed this internally between the authors and also during the last few core WG meetings. In general, we want to prevent that DoC is described too abstract, i.e. purely as a REST API, as we see the danger of incompatible implementations as a result from that. However, I agree that some sections in the current draft version are somewhat restating obvious CoAP behavior. In latest `main`, these sections were removed.

**Comment by miri64** [comment]
> In latest `main`, these sections were removed.

The latest `main` back then has since then been published as https://datatracker.ietf.org/doc/draft-lenders-dns-over-coap/04/ and those changes are still part of https://datatracker.ietf.org/doc/draft-ietf-core-dns-over-coap/. So this can be closed, I think.
