### ISSUE TITLE
How would we use DNR?

### ISSUE THREAD

**Issue by cabo** [core-wg/draft-dns-over-coap#22]
``` 
DHCP or Router Advertisement options [I-D.ietf-add-dnr]
```  

I'm not sure this is defined yet -- is it intended to be?

**Comment by miri64** [comment]
The draft for that is currently discussed in the add working group: https://datatracker.ietf.org/doc/draft-ietf-add-dnr/

**Comment by miri64** [comment]
> Does that draft explain how to refer to DoC?

Indeed, there seems to be some extra work required to make this work with DoC. From a quick read-through (specifically Section 3.1.5 of -13 of that draft) I'd say at least an ALPN needs to be defined (though how to do that with OSCORE or if it is even required in that case, I am not sure). The `port` should be a given.

Maybe this option is only suitable if one chooses to use CoAPS, as it seems very tailored to TLS and for OSCORE (or unencrypted CoAP use) we need another way (e.g. as mentioned a resource directory).

**Comment by EskoDijk** [comment]
We have now the DDR / DNR RFCs:
* https://datatracker.ietf.org/doc/html/rfc9462
* https://datatracker.ietf.org/doc/html/rfc9463

I was also wondering if these should be referenced and how discovery of DoC service might be done using such mechanisms.

**Comment by miri64** [comment]
https://github.com/core-wg/draft-dns-over-coap/pull/27

**Comment by miri64** [comment]
There is now https://datatracker.ietf.org/doc/draft-lenders-core-dnr/, which is referenced as of [-06](https://datatracker.ietf.org/doc/draft-ietf-core-dns-over-coap/06/) of the DoC draft.
